//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MStart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Server_DateTime { get; set; }
        public Nullable<System.DateTime> DateTime_UTC { get; set; }
        public Nullable<System.DateTime> Update_DateTime_UTC { get; set; }
        [Required(ErrorMessage = "Account number is required.")]
        [RegularExpression(@"^\d{7}$", ErrorMessage = "Account number must be 7 digits.")]
        [UniqueAccountNumber(ErrorMessage = "Account number must be unique across the system.")]

        public string Account_Number { get; set; }

        [Required(ErrorMessage = "Balance is required.")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Balance must be a valid decimal value.")]


        public decimal Balance { get; set; }

        [Required(ErrorMessage = "Currency is required.")]
        public string Currency { get; set; }

        [Required(ErrorMessage = "Status is required.")]
        public int Status { get; set; }


        public virtual User_Table User_Table { get; set; }
    }
}
