//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace MStart.Models
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class UniqueAccountNumberAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if (value != null)
            {
                string accountNumber = value.ToString();
                var entity = validationContext.ObjectInstance as Account; // تغيير 'Account' إلى اسم الكائن الخاص بك

                using (var db = new MStartEntities())
                {
                    bool isDuplicate = db.Accounts.Any(a => a.Account_Number == accountNumber && a.ID != entity.ID);
                    if (isDuplicate)
                    {
                        return new ValidationResult(ErrorMessage);
                    }
                }

            }
            return ValidationResult.Success;
        }
    }
}